export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const SEARCH_REPOSITORY = 'SEARCH_REPOSITORY';
export const NOTE_REPOSITORY = 'NOTE_REPOSITORY';
export const COLLEGE_REPOSITORY = 'COLLEGE_REPOSITORY';
export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';
